config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  
  devise_for :users
  
  
  resources :tweets do
    member do
      put "like", to: "tweets#like"
      put "dislike", to: "tweets#dislike"
    end
  end

  resources :users do
    get 'profile'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord

  has_many :tweets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  ## Validations
    validates :avatar, file_size: { less_than_or_equal_to: 5.megabytes },
                file_content_type: { allow: ['image/jpeg', 'image/png', 'image/gif'] }
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
   protected
      def configure_permitted_parameters
         devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password)}
         devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:avatar, :email, :password, :current_password)}
      end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!
    def index
        @tweets = Tweet.all
    end

    def new
        @tweet = Tweet.new
    end

    def create
        @tweet = Tweet.new(tweet_params)
        @tweet.user_id = current_user.id
        if @tweet.save
            redirect_to '/tweets#index'
        else
          render 'new'
        end
    end

    def destroy
        @tweet = Tweet.find(params[:id])
        @tweet.destroy
        redirect_to '/', :notice => "Your tweet has been deleted"
      end

    def like
        @tweet = Tweet.find(params[:id])
        @tweet.liked_by current_user
        redirect_to '/'
    end

    def dislike
        @tweet = Tweet.find(params[:id])
        @tweet.disliked_by current_user
        redirect_to '/'
    end

    private
    def tweet_params
        params.require(:tweet).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def profile
        @userid = params[:user_id]
        @userinfo = User.find(params[:user_id])
        @usercount = @userinfo.tweets
        @tweets=Tweet.all
    end

    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
    <title>Projet Hoot</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

  <div>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/tweets">Hoot</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
         <p class="navbar-text">
            <div class="navbar-text float-end">
        <% if user_signed_in? %>
          Logged in as: <br/>
           <button class="btn btn-sm btn-outline-secondary " type="button"> <strong> <%= current_user.email %></strong> </button>

          <% if current_user.avatar.present? %>
          <%= image_tag(current_user.avatar.variant(resize_to_fill: [50, 50]), class: "rounded-circle") %>
          <% else %>
          <img alt="image" class="rounded-circle" src="/assets/default_avatar_small.jpg">
          <% end %>
          
          <%= link_to ' Edit profile', edit_user_registration_path %> |
          <%= link_to ' My tweets', user_profile_path(current_user.id), :class => "bi bi-blockquote-right" %> |
          <%= link_to ' New tweet', new_tweet_path(@user), :class => "bi bi-pencil-square" %> |
          <%= link_to " Logout", destroy_user_session_path, method: :delete, :class => "bi bi-box-arrow-in-left"  %>
          <% else %>
          <%= link_to " Sign up", new_user_registration_path, :class => "bi bi-person-plus-fill"  %> |
          <%= link_to " Login", new_user_session_path, :class => "bi bi-box-arrow-in-left"  %>
          <% end %>
            </div>
          <%# <li class="nav-item active">
            <a class="nav-link" href="#">Homepage <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> %>
          </p>
        </ul>
      </div>
    </nav>
  </div>


    <div class= "container">
      <br/>
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/tweets/_form.html.erb
<div class="jumbotron">
 
          <% if current_user.avatar.present? %>
          <%= image_tag(current_user.avatar.variant(resize_to_fill: [100, 100]), class: "rounded-circle") %>
          <% else %>
          <img alt="image" class="rounded-circle" src="/assets/default_avatar_small.jpg">
          <% end %>
          <br/>  <br/>
           <h1 class="display-4"> New tweet</h1>
  <%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>
 
      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <p> <p> A penny for your thoughts ? </p>
  
    <% form.label :body%>
    
    <%= form.text_area :body, :id => 'body' %>
  </p>
 
  <div class="actions">
    <%= form.submit "Tweet it !", class:"btn btn-secondary" %>
  </div>
<% end %>
</div>

app/views/tweets/_tweet.html.erb
<div id="">
</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<br/>

<div class="jumbotron">
<h1 class="text-center"> Hoot Home </h1> 
<br/>  
<div class= "card p-3">

 <div class= "card-body" >
  <% @tweets.reverse.each do |tweet| %>
    <tr>
      <h1><%= link_to tweet.user.email, user_profile_path(tweet.user) %></h1>
      
          <% if tweet.user.avatar.present? %>
          <%= image_tag(tweet.user.avatar.variant(resize_to_fill: [50, 50]), class: "rounded-circle") %>
          <% else %>
          <%= image_tag("default_avatar_small.jpg", width: 50, :style => "border-radius: 100px") %>
          <% end %>
      <h2><td><%= tweet.body %></td></h2>
      <h5><td><%= tweet.created_at %></td></h5>
    </tr>

    <br/>
    <% if current_user == tweet.user %>
        <%= link_to "Delete", tweet_path(tweet.id), :confirm => "Are you sure?", :method => :delete, class:"btn btn-danger  " %>
    
    <% end %>
    <% if current_user.liked? tweet %>
    <%= link_to dislike_tweet_path(tweet.id), method: :put do %>
      <%= image_tag("like.png", :alt => "Like", height: 18, width: 20) %>
      <%= tweet.get_likes.size %>
      <% end %>

      <% else %>
      <%= link_to like_tweet_path(tweet), method: :put do %>
          <%= image_tag("dislike.png", :alt => "Like", height: 18, width: 20) %>
          <%= tweet.get_likes.size %>
        <% end %>
        <br/>  <br/>
        <hr>
    <% end %>
  <% end %>    
 
</div>
</div>
 <br/>
  
<button class= "btn btn-dark "> <i class="bi bi-pencil-square"></i> <%= link_to 'New Tweet', new_tweet_path(@user), :class => "text-decoration-none text-light"%> </button>
</div>

app/views/tweets/new.html.erb
<%# <h1>New tweet</h1> %>

<%= render "form", tweet: @tweet %>

<br>

<div class="btn btn-dark">
  <%= link_to "Back to tweets", tweets_path, :class => "text-decoration-none text-light" %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><% notice %></p>

<%= render "tweet" %>

<div>
  <%= link_to "Back to tweets", tweets_path,:class => "btn btn-secondary text-decoration-none text-light" %>


<br/> <br/>

    <%= button_to "Destroy this tweet", @tweet, method: :delete,:class => "btn btn-danger text-decoration-none text-light" %>

</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/profile.html.erb
<div class="jumbotron">
  <h1 class="display-4">Profile</h1>
  
<div>
<h1> Email: <%= @userinfo.email %></h1>
<h2>You have tweeted <%= @usercount.size %> time(s).</h2>
</div>
 
<div>
<% @tweets.reverse.each do |tweet| %>
  <% if @userinfo == tweet.user %>
    <p>
      <tr>
        <div  class="tweet card p-3">
          <h3 class="black"><td><%= link_to tweet.user.email, user_profile_path(tweet.user) %></td></h3>
          <h2> 
          <% if current_user.avatar.present? %>
          <%= image_tag(current_user.avatar.variant(resize_to_fill: [50, 50]), class: "rounded-circle") %>
          <% else %>
          <img alt="image" class="rounded-circle" src="/assets/default_avatar_small.jpg">
          <% end %>
          <td><%= tweet.body %></td></h2>
          <h5><td><%= tweet.created_at %></td></h5>
          <span class="twitter-button">  
            <%= button_to "Delete", tweet_path(tweet.id), :confirm => "Are you sure?", :method => :delete, class: "btn btn-danger" %> 
          </span>
        </div>
      </tr>
    </p>
  <% end %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<p style="color:green"><%= notice %></p>

<%= render "user" %>

<div>
  <%= link_to "Back to users", tweets_path, :class => "btn btn-secondary text-decoration-none text-light" %>
<br/> <br/>
  <%= button_to "Do you really want to disconnect?", @user, method: :delete, :class => "btn btn-danger text-decoration-none text-light" %>
</div>